# Generated by Django 3.2.6 on 2021-09-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_auto_20210829_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('propertie', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('monitzation', models.CharField(max_length=100)),
                ('google', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('visitsdays', models.CharField(max_length=100)),
                ('visitsmonth', models.CharField(max_length=100)),
                ('check', models.CharField(max_length=100)),
            ],
        ),
    ]
