# Generated by Django 3.2.6 on 2021-09-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_selldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selldata',
            name='check',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='days',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='google',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='monitzation',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='month',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='propertie',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='visitsdays',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='visitsmonth',
        ),
    ]
